openapi: 3.0.3
info:
  title: Book-King.org API
  description: This is an API for the Book-King.org website.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server address
paths:
  /static/image/{imageId}:
    get:
      summary: Get image by imageId
      operationId: getImageById
      description: Get image with the provided database pk id.
      parameters:
        - $ref: '#/components/parameters/imageId'
      responses:
        '200':
          description: Success. Image found.
          content:
            image/jpeg: {}
            image/gif: {}
            image/png: {}
        '404':
          description: Image with the provided imageId was not found.
components:
  parameters:
    imageId:
      name: imageId
      in: path
      description: Image database pk id.
      required: true
      schema:
        type: integer
